version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "coffeejunk"
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "coffeejunk"
