name: CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: Install PostgreSQL 11 client
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Cache RVM, Ruby and Bundler
      id: ruby-cache
      uses: actions/cache@v1
      with:
        path: ~/.rvm
        key: ${{ runner.os }}-ruby-${{ hashFiles('.ruby-version') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Set up Ruby from .ruby-version
      if: steps.ruby-cache.outputs.cache-hit != 'true'
      run: |
        curl -sSL https://get.rvm.io | bash
        source $HOME/.rvm/scripts/rvm
        rvm install $(cat .ruby-version) --binary
        rvm --default use $(cat .ruby-version)
        gem install bundler

    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Bundle Install
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Build App
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        source $HOME/.rvm/scripts/rvm
        bin/rails db:setup

    - name: Run Tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
        SES_SMTP_EMAIL_ADDRESS: test@example.com
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle exec rails spec

    - name: Style Check
      run: |
        source $HOME/.rvm/scripts/rvm
        gem install standard
        standardrb
